# docker-compose.yml
version: '3.8'
services:
  orchestrator:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./orchestrator:/app/orchestrator
    environment:
      - ENV=development